version: 1.0.{build}
install:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack
test_script:
- dotnet test --test-adapter-path:. --logger:Appveyor test\XZ.Net.Tests\XZ.Net.Tests.csproj
artifacts:
- path: '**\*.nupkg'
