version: 1.0.{build}
install:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
test:
  assemblies:
  - 'test\**\*.Tests.dll'
after_build:
- cmd: dotnet pack
artifacts:
- path: '**\*.nupkg'
